---
title: "Requirements Management Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(highcharter)
library(ggvis)
```



```{r}

rm_data<- read.csv("U:/WORK_RM_COMPLETE_DATASET.csv",header =TRUE)
rm_data <- rm_data %>% filter(rm_data$SEQUENCE_NB == 1)

rm_data_1 <- filter(rm_data, rm_data$REQUIREMENT_ID>150000)


```



Requirement Management Metrics
=====================================
Column {data-width=650}
-----------------------------------------------------------------------

### Count by Transaction

```{r}
p1 <- rm_data %>%
         group_by(TXN_TYPE_DESC_X) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~TXN_TYPE_DESC_X,
                 y = ~count,
                 color = "blue",
                 type = 'bar') %>%
layout(xaxis = list(title = "COUNT BY TXN_TYPE"),
yaxis = list(title = 'Count'))
p1
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
library(plotly)

Animals <- c("giraffes", "orangutans", "monkeys")
SF_Zoo <- c(20, 14, 23)
LA_Zoo <- c(12, 18, 29)
data <- data.frame(Animals, SF_Zoo, LA_Zoo)

p <- plot_ly(data, x = ~Animals, y = ~SF_Zoo, type = 'bar', name = 'SF Zoo') %>%
  add_trace(y = ~LA_Zoo, name = 'LA Zoo') %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack')
p

```

### Chart C

```{r}

```


Monthly RM Pivot Table
=========================================

```{r}

rpivotTable(rm_data_1,
            aggregatorName = "Count",
            cols= "TXN_TYPE_DESC_X",
            rows = "SUPERVISOR_NAME",
            rendererName = "Heatmap")
```

