---
title: "Disbursement Unneccessary Edits Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: []
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(highcharter)
library(ggvis)
```


```{r}

data_2 <- read.csv("O:/Business Process Engineering/BPEAs/Automated SAS Projects/Automated Report Data/Edits Dashboard Data/WORK_ASSOCIATE_LOOPING_DATA.csv",header =TRUE)

data_4<- read.csv("O:/Business Process Engineering/BPEAs/Automated SAS Projects/Automated Report Data/Edits Dashboard Data/ADVANCED_DISBURSEMENTS_TXN_STATS.csv",header =TRUE)

data_4$Processing_Time <- data_4$PROCESSING_TIME.min._Sum
data_4$PROCESSING_TIME.min._Sum <- NULL
data_4$PROCESSING_TIME.min._N <- NULL
data_4$FIRST_EVENT_DATE1 <- NULL

data_6 <- filter(data_4, data_4$Processing_Time <90)

data_7 <- filter(data_4, data_4$EDIT_COUNT <50)

# data_6 <- filter(data_4, data_4$THROUGHPUT_TIME.hours. < 12)
# data_5 <- filter(data_4, data_4$ELAPSED_TIME_NB_Sum < 3600)
# data_4$EVENT_COUNT<- NULL
# data_4$ELAPSED_TIME_NB_Mean <- NULL
# data_4$ELAPSED_TIME_NB_Sum <-NULL
# names(data_4)<- c("TXN_ID","DATE","TIME","TIMESTAMP","TXN_TYPE","EDIT_COUNT","THROUGHPUT_TIME.hours.","Processing_Time_min")

```

```{r}
mycolors <- c("blue", "#FFC125", "darkgreen", "darkorange")
```

Interactive Data Visualization
=====================================

Row
-------------------------------

### Total Unneccessary Edits for the week, these are edits that were not cleared after the user took action on the piece of work and therefore the piece of work could not move on to the next skill
```{r}
valueBox(NROW(data_2))
```

Row
-------------------------------

### Count by Manager

```{r}
p1 <- data_2 %>%
         group_by(SUPERVISOR_NAME) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~SUPERVISOR_NAME,
                 y = ~count,
                 color = "blue",
                 type = 'bar') %>%
layout(xaxis = list(title = "COUNT BY MANAGER"),
yaxis = list(title = 'Count'))
p1
```

### Top Transaction Type Counts

```{r}
p2 <- data_2 %>%
         group_by(Transaction.Type) %>%
         summarise(count = n()) %>%
         filter(count>50) %>%
         plot_ly(labels = ~Transaction.Type,
                 values = ~count,
                 marker = list(colors = mycolors)) %>%
         add_pie(hole = 0.2) %>%
         layout(xaxis = list(zeroline = F,
                             showline = F,
                             showticklabels = F,
                             showgrid = F),
                yaxis = list(zeroline = F,
                             showline = F,
                             showticklabels=F,
                             showgrid=F))
p2
```

### Edit Counts over Time

```{r}


p3 <- data_2 %>%
         group_by(Date) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~Date,
                 y = ~count,
                 color = "red",
                 type = 'bar') %>%
layout(xaxis = list(title = "COUNT BY Date"),
yaxis = list(title = 'Count'))
p3
```

Row
------------------------------------
### Scatter Plot of Associate Counts

```{r}

p1 <- data_2 %>%
         group_by(Associate_Name) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~Associate_Name,
                 y = ~count,
                 color = "yellow",
                 type = 'bar') %>%
layout(xaxis = list(title = "COUNT BY ASSOCIATE"),
yaxis = list(title = 'Count'))
p1
```




Pivot Table
=========================================

```{r}

data_pivot <- data_2
rpivotTable(data_pivot,
            aggregatorName = "Count",
            rendererName = "Heatmap")
```




Advanced Disbursement Metrics
=====================================

Row
-------------------------------

### TXN Processing Time


```{r}

p <- plot_ly(data_6, x =~Transaction.Type,y = ~Processing_Time, type = "box")
p
```


Row
------------------------------------

### Processing Time Compared to Total Edits Count
```{r}

fit <- lm(EDIT_COUNT ~ Processing_Time, data = data_7)

data_7 %>% 
  plot_ly(x = ~Processing_Time) %>% 
  add_markers(y = ~EDIT_COUNT) %>% 
  add_lines(x = ~Processing_Time, y = fitted(fit))
```

Row
------------------------------------

### Relationship Total Edits and Transactional Processing Time
```{r}
valueBox(cor(data_6$Processing_Time,data_6$EDIT_COUNT),
         icon = "fa-area-chart")
```



Advanced Disbursements Pivot Table
=========================================

```{r}


rpivotTable(data_4,
            aggregatorName = "Average",
            rows = "Transaction.Type",
            rendererName = "Heatmap")
```


