---
title: "Disbursement Unneccessary Edits Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: []
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(highcharter)
library(ggvis)
```


```{r}

data_2 <- read.csv("U:/WORK_ASSOCIATE_LOOPING_DATA.csv",header =TRUE)
data_4<- read.csv("U:/WORK_ADVANCED_DISBURSEMENTS_METRICS.csv",header =TRUE)
data_4$Processing_Time <- data_4$ELAPSED_TIME_NB_Sum/60
data_6 <- filter(data_4, data_4$THROUGHPUT_TIME.hours. < 12)
data_5 <- filter(data_4, data_4$ELAPSED_TIME_NB_Sum < 3600)
data_4$EVENT_COUNT<- NULL
data_4$ELAPSED_TIME_NB_Mean <- NULL
data_4$ELAPSED_TIME_NB_Sum <-NULL
names(data_4)<- c("TXN_ID","DATE","TIME","TIMESTAMP","TXN_TYPE","EDIT_COUNT","THROUGHPUT_TIME.hours.","Processing_Time_min")

```

```{r}
mycolors <- c("blue", "#FFC125", "darkgreen", "darkorange")
```

Interactive Data Visualization
=====================================

Row
-------------------------------

### Total Potentially Unneccessary Edits for the Week, these are edits that should of been cleared by the previous user, but were not and then populated again for the next user, if you think any of the edits should not be included in this list feel free to contact corey.arnouts@jackson.com as the list can be constantly evolving
```{r}
valueBox(NROW(data_2))
```

Row
-------------------------------

### Count by Manager

```{r}
p1 <- data_2 %>%
         group_by(SUPERVISOR_NAME) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~SUPERVISOR_NAME,
                 y = ~count,
                 color = "blue",
                 type = 'bar') %>%
layout(xaxis = list(title = "COUNT BY MANAGER"),
yaxis = list(title = 'Count'))
p1
```

### Top Transaction Type Counts

```{r}
p2 <- data_2 %>%
         group_by(Transaction.Type) %>%
         summarise(count = n()) %>%
         filter(count>50) %>%
         plot_ly(labels = ~Transaction.Type,
                 values = ~count,
                 marker = list(colors = mycolors)) %>%
         add_pie(hole = 0.2) %>%
         layout(xaxis = list(zeroline = F,
                             showline = F,
                             showticklabels = F,
                             showgrid = F),
                yaxis = list(zeroline = F,
                             showline = F,
                             showticklabels=F,
                             showgrid=F))
p2
```

### Edit Counts over Time

```{r}


p3 <- data_2 %>%
         group_by(Date) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~Date,
                 y = ~count,
                 color = "red",
                 type = 'bar') %>%
layout(xaxis = list(title = "COUNT BY Date"),
yaxis = list(title = 'Count'))
p3
```

Row
------------------------------------
### Scatter Plot of Associate Counts

```{r}
#data_2 <-order(data_2,data_2$SUPERVISOR_NAME)
p1 <- data_2 %>%
         group_by(NAME) %>%
         summarise(count = n()) %>%
         plot_ly(x = ~NAME,
                 y = ~count,
                 color = "yellow",
                 type = 'bar') %>%
layout(xaxis = list(title = "COUNT BY ASSOCIATE"),
yaxis = list(title = 'Count'))
p1
```




Pivot Table
=========================================

```{r}
#data_2$Date_num <- as.numeric(data_2$Date)

rpivotTable(data_2,
            aggregatorName = "Count",
            cols= "name",
            rows = "SUPERVISOR_NAME",
            rendererName = "Heatmap")
```




Advanced Disbursement Metrics
=====================================

Row
-------------------------------

### TXN Processing Time


```{r}

p <- plot_ly(data_5, x =~TXN_TYPE ,y = ~Processing_Time, type = "box")
p
```


### Throughput Time by TXN
```{r}


p <- plot_ly(data_6, x =~TXN_TYPE ,y = ~data_6$THROUGHPUT_TIME.hours., type = "box")
p
```

Row
------------------------------------

### Processing Time Compared to Edits Count
```{r}

fit <- lm(Frequency.Count ~ Processing_Time, data = data_6)

data_6 %>% 
  plot_ly(x = ~Processing_Time) %>% 
  add_markers(y = ~Frequency.Count) %>% 
  add_lines(x = ~Processing_Time, y = fitted(fit))
```

Row
------------------------------------

### Relationship between Touches and Processing Time
```{r}
valueBox(cor(data_6$Processing_Time,data_6$Frequency.Count),
         icon = "fa-area-chart")
```



Advanced Disbursements Pivot Table
=========================================

```{r}


rpivotTable(data_4,
            aggregatorName = "Average",
            rows = "TXN_TYPE",
            rendererName = "Heatmap")
```


